-- AlterTable
ALTER TABLE "Hen" ALTER COLUMN "dailyYield" SET DEFAULT 1;

-- AlterTable
ALTER TABLE "Payment" ADD COLUMN     "paid" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "used" BOOLEAN NOT NULL DEFAULT false,
ALTER COLUMN "henId" DROP NOT NULL,
ALTER COLUMN "txHash" DROP NOT NULL;
